openapi: 3.0.0
paths:
  /file:
    post:
      operationId: AppController_uploadFile
      parameters: []
      requestBody:
        required: true
        description: ''
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/FileUploadDto'
      responses:
        '201':
          description: ''
      tags:
        - file
    get:
      operationId: AppController_Hi
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - file
info:
  title: GeneratorCSV Buffer
  description: A simple file uploading. CSV only.
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas:
    FileUploadDto:
      type: object
      properties:
        file:
          type: string
          format: binary
      required:
        - file
