openapi: 3.0.0
info:
  title: CSV Buffer
  description: Entre com CSV e resulte seu binário
  version: '1.0'
paths:
  /file:
    post:
      operationId: AppController_uploadFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Apenas arquivos CSV
      responses:
        '201':
          description: Created
      tags:
        - file
    get:
      operationId: AppController_Hi
      responses:
        '200':
          description: OK
      tags:
        - file
